name: Build and Publish Python Package

on:
  workflow_run:
    workflows: ["Test Python SDK"]
    branches: [main]
    types: [completed]

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest
    # Only run if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # Need to check out the commit that was tested
        ref: ${{ github.event.workflow_run.head_sha }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Validate package
      run: |
        pip install -e ".[dev]"
        python -c "from realitydefender.__version__ import __version__; print(f'Building version: {__version__}')"
    
    - name: Build package
      run: |
        python -m build
    
    - name: Verify build artifacts
      run: |
        twine check dist/*
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true 
