name: Test Python SDK

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/**'

jobs:
  test-python-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Lint with flake8
      working-directory: ./python
      run: |
        flake8 src tests examples
        
    - name: Type check with mypy
      working-directory: ./python
      run: |
        mypy src tests examples
        
    - name: Test with pytest
      working-directory: ./python
      run: |
        pytest tests/ --cov=realitydefender --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./python/coverage.xml
        flags: python
        name: python-sdk-codecov
        fail_ci_if_error: true 
